<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Debug\Module'                        => __DIR__ . '/Module.php',
    'Debug\Controller\IndexController' => __DIR__ . '/src/Debug/Controller/IndexController.php',
    'DebugTest\Framework\TestCase'        => __DIR__ . '/tests/Debug/Framework/TestCase.php',
    'DebugTest\SampleTest'                => __DIR__ . '/tests/Debug/SampleTest.php',
);
